import json
import os
from datetime import datetime

def generate_final_report(report_data):
    """
    Generates a beautifully formatted Markdown report from the unit data.
    """
    summary = report_data.get("unit_summary", {})
    metadata = summary.get("metadata", {})
    summary_marks = summary.get("summary_marks", {})
    flags = report_data.get("validation_flags", [])
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report = f"""# Thai Election OCR Prototype: Final Findings

**Date**: {timestamp}
**Target Form**: สส. 5 ทับ 18 (Huai Khot Unit 2)
**Prototype Objective**: Demonstrate the limitations of raw OCR on handwritten Thai election reports.

---

## 📊 Summary Metrics

| Metric | Score | Status |
| :--- | :--- | :--- |
| **Integrity Score** | **{report_data.get('integrity_score', 0.0):.2f}** / 1.00 | {"⚠️ REVIEW REQUIRED" if report_data.get('integrity_score', 0.0) < 0.9 else "✅ PASS"} |
| **Mean OCR Confidence** | **{report_data.get('mean_confidence', 0.0):.2f}** | {"🔴 LOW" if report_data.get('mean_confidence', 0.0) < 0.6 else "🟢 OK"} |
| **Validation Flags** | **{len(flags)}** | {"🚩 TRIGGERED" if flags else "NONE"} |

---

## 🛠️ Extraction Details

### Metadata Extraction
- **Total Voters (1.1)**: `{metadata.get('total_voters', {}).get('val', 'N/A')}`
- **Attendees (1.2)**: `{metadata.get('attendees', {}).get('val', 'N/A')}`

### Ballot Accuracy
- **Good Ballots**: `{summary_marks.get('good_ballots', {}).get('val', 'N/A')}`
- **Bad Ballots**: `{summary_marks.get('bad_ballots', {}).get('val', 'N/A')}`
- **No Vote**: `{summary_marks.get('novote_ballots', {}).get('val', 'N/A')}`

---

## 🚩 Validation Analysis

The automated validation layer identified the following issues in the raw OCR output:

"""
    if flags:
        for flag in flags:
            report += f"> [!{ 'CAUTION' if flag['severity'] == 'CRITICAL' else 'IMPORTANT' if flag['severity'] == 'HIGH' else 'WARNING' }]\n"
            report += f"> **{flag['type']}**: {flag['message']}\n\n"
    else:
        report += "_No validation flags triggered._\n"

    report += """
---

## 📝 Conclusion

The prototype successfully validates the hypothesis that **raw OCR is insufficient** for reliable Thai election digitizing without a robust post-processing and human-verification layer. 

### Key Lessons:
1. **Layout Ambiguity**: OCR frequently merges section numbers (e.g., "1.1") into data fields, leading to "Polluted EXTRACTION."
2. **Handwriting Sensitivity**: Low confidence scores (mean ~0.50) accurately reflect the difficulty of the task.
3. **Implicit Verification**: Mathematical cross-checks (Validation Layer) are critical for filtering faulty data.

---
_Generated by Antigravity Thai Election OCR Pipeline_
"""
    return report

def main():
    input_file = "data/output/unit_report.json"
    output_file = "FINAL_REPORT.md"
    
    if not os.path.exists(input_file):
        print(f"Error: {input_file} not found.")
        return
        
    with open(input_file, 'r', encoding='utf-8') as f:
        report_data = json.load(f)
        
    final_md = generate_final_report(report_data)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(final_md)
        
    print(f"Final Project Report generated: {output_file}")

if __name__ == "__main__":
    main()
